dist: trusty
sudo: required

install:
 - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.deb
 - sudo dpkg -i /tmp/hugo.deb

script: hugo

deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY
  secret_access_key: $GCS_SECRET_KEY
  bucket: kholodilov.me
  acl: public-read
  local-dir: public
  skip_cleanup: true
  on:
    repo: kholodilov/kholodilov.me
