language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo
deploy:
  provider: gcs
  access_key_id: $GCS_ACCESS_KEY
  secret_access_key: $GCS_SECRET_KEY
  bucket: www.kholodilov.me
  acl: public-read
  local-dir: public
  skip_cleanup: true
  on:
    repo: kholodilov/kholodilov.me
